language: java
jdk:
  - openjdk17

branches:
  only:
    - develop
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/coffeekiosk-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: coffeekiosk-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: develop
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: coffeekiosk-build
    key: coffeekiosk-webservice.zip
    bundle_type: zip
    application: coffeekiosk-webservice
    deployment_group: coffeekiosk-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: develop

notifications:
  email:
    recipients:
      - ugs1575@naver.com